import { createReplayTimeline, type ReplayTimeline } from '../../../packages/replay/src/index.js'

export const mockReplay: ReplayTimeline = createReplayTimeline({
  round: 3,
  duration: 24,
  summary: 'Blue wins by disable after trapping Red against the west rail.',
  events: [
    {
      t: 0,
      type: 'spawn',
      bot: 'red',
      position: [-8, 0, 0],
      rotation: [0, 90, 0],
    },
    {
      t: 0,
      type: 'spawn',
      bot: 'blue',
      position: [8, 0, 0],
      rotation: [0, -90, 0],
    },
    {
      t: 3,
      type: 'move',
      bot: 'blue',
      from: [8, 0, 0],
      to: [3, 0, -2],
      duration: 1.15,
      easing: 'ease_in_out',
    },
    {
      t: 3.25,
      type: 'move',
      bot: 'red',
      from: [-8, 0, 0],
      to: [-4.7, 0, -1.15],
      duration: 0.95,
      easing: 'ease_in_out',
    },
    {
      t: 5.35,
      type: 'move',
      bot: 'blue',
      from: [3, 0, -2],
      to: [0.85, 0, -1.1],
      duration: 0.72,
      easing: 'ease_out',
      contactIntent: true,
    },
    {
      t: 5.55,
      type: 'move',
      bot: 'red',
      from: [-4.7, 0, -1.15],
      to: [-2.55, 0, -2.8],
      duration: 0.78,
      easing: 'ease_out',
      contactIntent: true,
    },
    {
      t: 7,
      type: 'weapon_fire',
      bot: 'red',
      weaponSlot: 'weaponA',
      sourceBlockId: 'spinner',
      sourcePartId: 'Weapon_Spinner_Large',
      phase: 'release',
      style: 'spinner',
      targetPosition: [0.85, 0, -1.1],
    },
    {
      t: 8.2,
      type: 'move',
      bot: 'blue',
      from: [0.85, 0, -1.1],
      to: [2.15, 0, -3.15],
      duration: 0.88,
      easing: 'ease_in_out',
    },
    {
      t: 8.35,
      type: 'move',
      bot: 'red',
      from: [-2.55, 0, -2.8],
      to: [-2, 0, -4],
      duration: 0.65,
      easing: 'ease_out',
    },
    {
      t: 9.45,
      type: 'weapon_fire',
      bot: 'blue',
      weaponSlot: 'weaponA',
      controlCue: 'deploy',
      sourceBlockId: 'net',
      sourcePartId: 'Weapon_Net',
      phase: 'deploy',
      style: 'net',
      targetPosition: [-2, 0, -4],
    },
    {
      t: 9.65,
      type: 'ability',
      bot: 'blue',
      ability: 'laser_lance',
      weaponSlot: 'weaponA',
      target: 'red',
      targetPosition: [-2, 0, -4],
    },
    {
      t: 10,
      type: 'impact',
      attacker: 'blue',
      defender: 'red',
      damage: 18,
      position: [-2, 0, -4],
    },
    {
      t: 11.15,
      type: 'ability',
      bot: 'blue',
      ability: 'drone_swarm',
      weaponSlot: 'weaponB',
      target: 'red',
      targetPosition: [-3, 0, -3],
    },
    {
      t: 13,
      type: 'hazard',
      hazard: 'center saw',
      bot: 'red',
      damage: 10,
      position: [-3, 0, -3],
    },
    {
      t: 16,
      type: 'damage',
      bot: 'red',
      amount: 16,
      remainingHealth: 22,
      blockId: 'front-plate',
      partId: 'Armor_Front_Plate',
      partRemainingHealth: 0,
      partMaxHealth: 16,
    },
    {
      t: 16.25,
      type: 'part_detach',
      bot: 'red',
      blockId: 'front-plate',
      partId: 'Armor_Front_Plate',
      position: [-3, 0.2, -3],
      sourcePosition: [3, 0, -2],
      impactPosition: [-3, 0, -3],
      impulse: [-1.55, 1.05, -0.28],
      angularImpulse: [0.34, 1.2, 0.72],
      fractureSeverity: 0.92,
      damageCause: 'hazard',
    },
    {
      t: 22,
      type: 'knockout',
      bot: 'red',
      cause: 'drive disabled',
    },
  ],
})

export const abilityProofReplay: ReplayTimeline = createReplayTimeline({
  round: 4,
  duration: 6,
  summary: 'Ability and part detach readability proof.',
  events: [
    {
      t: 0,
      type: 'spawn',
      bot: 'red',
      position: [-3.15, 0, -0.85],
      rotation: [0, 70, 0],
    },
    {
      t: 0,
      type: 'spawn',
      bot: 'blue',
      position: [3.95, 0, 1.65],
      rotation: [0, -110, 0],
    },
    {
      t: 0.65,
      type: 'move',
      bot: 'red',
      from: [-3.15, 0, -0.85],
      to: [-1.45, 0, -2.35],
    },
    {
      t: 0.65,
      type: 'move',
      bot: 'blue',
      from: [3.95, 0, 1.65],
      to: [1.7, 0, -0.55],
    },
    {
      t: 1.55,
      type: 'weapon_fire',
      bot: 'blue',
      weaponSlot: 'weaponA',
      controlCue: 'deploy',
      sourceBlockId: 'net',
      sourcePartId: 'Weapon_Net',
      phase: 'deploy',
      style: 'net',
      targetPosition: [-1.36, 0, -2.28],
    },
    {
      t: 1.72,
      type: 'ability',
      bot: 'blue',
      ability: 'laser_lance',
      weaponSlot: 'weaponA',
      target: 'red',
      targetPosition: [-1.22, 0, -2.18],
    },
    {
      t: 1.88,
      type: 'ability',
      bot: 'blue',
      ability: 'drone_swarm',
      weaponSlot: 'weaponB',
      target: 'red',
      targetPosition: [-1.65, 0, -1.92],
    },
    {
      t: 2.06,
      type: 'impact',
      attacker: 'blue',
      defender: 'red',
      damage: 20,
      position: [-1.24, 0, -2.16],
    },
    {
      t: 2.14,
      type: 'damage',
      bot: 'red',
      amount: 20,
      remainingHealth: 32,
      blockId: 'front-plate',
      partId: 'Armor_Front_Plate',
      partRemainingHealth: 0,
      partMaxHealth: 16,
    },
    {
      t: 2.2,
      type: 'part_detach',
      bot: 'red',
      blockId: 'front-plate',
      partId: 'Armor_Front_Plate',
      position: [-1.24, 0.28, -2.16],
      sourcePosition: [1.7, 0, -0.55],
      impactPosition: [-1.24, 0, -2.16],
      impulse: [-1.75, 1.2, -0.96],
      angularImpulse: [0.64, 1.45, 0.92],
      fractureSeverity: 1,
      damageCause: 'weapon',
    },
  ],
})
