#version 330
// Persistent foam state. Foam is never re-noised per frame: it is generated by
// breaking, carried by the surface flow, stretched, aged and only then faded.
// Channels: r fresh whitewater, g persistent foam, ba material coordinate.
in vec2 uv;
out vec4 outFoam;

#include "common.glsl"

uniform sampler2D texGeom, texFlow, texPrev, texPath;
uniform float uDt;
uniform float uTauFresh, uTauPersist;
uniform float uInjBreak, uInjWhitecap, uInjShore;
uniform float uRelax;        // seconds for material coords to relax back
uniform float uDiffuse;
uniform float uFoamBlend;   // per-step weight of the diffused neighbourhood
uniform float uFoamDeepFade; // how hard offshore whitecap injection is cut
uniform float uFoamDeepTau;  // deep-water persistence multiplier (the anti-slab cut)
uniform float uBreakVis;     // breaker resolvability at this camera; see wave.frag
uniform float uShoreFloor;   // shore injection that arrives with NO wave breaking there
uniform float uInjFilament, uInjCrestW, uInjCrestLevel, uInjCrestBoost, uInjCrestRun;
uniform float uInjPatch, uInjPatchScale;
uniform float uFirst;        // 1.0 on the very first step

void main()
{
    vec2 px = uv * uRes;
    vec4 M = texture(texM, uv);
    float water = M.x;
    vec4 G = texture(texG, uv);
    float sdf = G.w;
    vec4 flow4 = texture(texFlow, uv);
    vec2 flow = flow4.xy;
    vec4 geom = texture(texGeom, uv);
    float breaking = geom.w;
    float whitecap = flow4.w;

    // ---- semi-Lagrangian backtrace ---------------------------------------
    vec2 back = px - flow * uDt;
    vec2 buv = clamp(back / uRes, vec2(0.0015), vec2(0.9985));
    vec4 prev = texture(texPrev, buv);

    // A touch of diffusion so sheets break into patches instead of staying solid
    // -- but only a touch. At 48 substeps a second, a 0.30 blend toward the
    // 1-px neighbourhood is near-total smoothing within a second of foam life,
    // and that, not the erosion field, is what made whitewater read as soft
    // cotton wool instead of painted surf.
    vec2 d = uDiffuse / uRes;
    vec4 blur = 0.25 * (texture(texPrev, buv + vec2(d.x, 0.0))
                      + texture(texPrev, buv - vec2(d.x, 0.0))
                      + texture(texPrev, buv + vec2(0.0, d.y))
                      + texture(texPrev, buv - vec2(0.0, d.y)));
    prev = mix(prev, blur, uFoamBlend);

    // ...and it must fade faster out there, too. The cut is preset-driven now:
    // 0.18 was written when injection was dense enough to accumulate ice floes.
    // With the threshold-quadratic whitecap (rare, group-clustered events) the
    // accumulation cannot happen, and the literature wants residual foam to
    // OUTLIVE fresh several-fold at heavy states (stage B >> stage A; notes R6)
    // -- offshore foam should die by not being reinjected, not by being
    // triple-killed.
    // FOAM MUST NOT ACCUMULATE INTO A FIELD THE CAMERA CANNOT RESOLVE.
    //
    // This is the last author of the capital-tier fabric, and it took a
    // phase-invariant metric to see: two captures of one build differ by wave
    // phase, so nothing here can be judged by eye or by image difference. On
    // water-masked captures at the capital camera, foam was the ONLY author of
    // both the fine dashes (high-frequency energy 25.6 -> 8.7 with injection
    // off) and the broad diagonal bands (band energy 31.8 -> 14.2), where six
    // tone painters, the crest strokes, the sky/gloss family and even the wave
    // field itself each moved them by ~5 or by nothing at all. Injection is
    // already rare out there -- a swash ribbon over 1% of the water -- but
    // seven seconds of persistence carried and held it until it covered the
    // sea. Cutting lifetime alone (0.12x) collapsed the fabric to what killing
    // injection does, which is the measurement this gate is built on.
    //
    // So lifetime rides breaker resolvability: close in, foam lives its tuned
    // seven seconds and streaks the way surf does; from the map it dies about
    // as fast as it is born, which leaves exactly the coast ribbon a wide shot
    // should have and nothing on the open sea.
    float tauLoD = mix(0.12, 1.0, uBreakVis);
    float tauP = uTauPersist * tauLoD * mix(1.0, uFoamDeepTau, smoothstep(15.0, 38.0, max(texture(texP, uv).w, 0.35)));
    float fresh   = prev.r * exp(-uDt / max(uTauFresh * mix(0.30, 1.0, uBreakVis), 1e-3));
    float persist = prev.g * exp(-uDt / max(tauP, 1e-3));

    // Material coordinates ride with the flow. A material coordinate is *carried*,
    // not offset: M(x, t+dt) = M(x - u dt, t). Adding (px - back) as well made the
    // field accumulate a per-step drift, which decorrelated neighbouring pixels
    // and turned the lace lookup into per-pixel noise.
    vec2 mat = prev.ba;
    if (uFirst > 0.5) mat = px;
    mat = mix(mat, px, clamp(uDt / max(uRelax, 1e-3), 0.0, 1.0));

    // ---- injection --------------------------------------------------------
    float shoreZone = M.y;
    float hn = texture(texGeom, uv).x;
    // Offshore whitecap foam must not accumulate. In deep water a whitecap is a
    // transient streak on one crest; letting it build with the same persistence
    // as shore whitewater grew solid white slabs that read as ice floes.
    float depthPx = max(texture(texP, uv).w, 0.35);
    // This is ONE of three multiplicative suppressions of offshore foam. The
    // others are the persistence cut (tauP -> 0.18x above) and the render
    // threshold (uFoamDeepThr). Each alone is enough to zero the result, so
    // sweeping any one of them changes the render by nothing -- injWhitecap was
    // measured across a 17x range with byte-identical output, and the offshore
    // suppression trio across 3x likewise.
    //
    // Keep the anti-slab mechanism where it belongs: SHORT LIFETIME offshore, so
    // whitecap foam is a transient streak that cannot accumulate into the ice
    // floes this was written to stop. Do not also refuse to create it.
    float deepFade = 1.0 - uFoamDeepFade * smoothstep(15.0, 38.0, depthPx);
    // ---- filamentary injection ---------------------------------------------
    // Foam is BORN at breaking crests, and a crest is a LINE. Injecting on the
    // broad `breaking` and `whitecap` fields makes it born as a patch, and a
    // patch stays a patch: measured, foam lives 6.4 s here, while real filaments
    // are folded out of surface material over minutes of circulation. Shear
    // cannot make a filament from a blob in six seconds -- adding divergence-free
    // curl shear moved neighbour coherence 0.281 to 0.293 and nothing else, and
    // cutting the diffusion so shear could act made the foam field WORSE (0.543
    // to 0.328), because the diffusion was what kept it smooth.
    //
    // So the filament has to be there at birth. Gate injection by the crest
    // contour and boost to compensate for the smaller area it covers.
    float hPath = texture(texPath, uv).x;
    float crestLine = contourLine(hPath, uInjCrestLevel, uInjCrestW);
    float lineGate = mix(1.0, crestLine * uInjCrestBoost, uInjFilament);
    // A long line times a granular field is a row of dots.
    //
    // crestLine is a clean smooth contour of hPath -- one cosine -- and running
    // it into `breaking * uInjBreak + whitecap * uInjWhitecap` undid that
    // immediately: whitecap is sparse and granular (mean 0.04, above 0.1 on 7.8%
    // of pixels), so foam was BORN as dots sitting on a line rather than as the
    // line. Nothing downstream can recover a run from that, which is why longer
    // persistence, faster advection and the filament gate itself each moved
    // measured streak reach by only a few tuned px against a reference at 134.8.
    //
    // A wave does not break at a point. It breaks along a stretch of its crest,
    // and every part of that stretch makes foam. So let a trigger recruit along
    // the crest TANGENT: take the strongest breaking within uInjCrestRun either
    // way along the crest, and the run injects as a run. Across the tangent
    // nothing is widened, so the filament stays as thin as the contour draws it.
    // Whitecapping is PATCHY, and this is what makes a sea read as a textile
    // when it is not. A real crest does not break evenly along its whole length:
    // most of it is unbroken water and a few stretches of it are white, and which
    // stretches those are changes from crest to crest. Every band here broke the
    // same amount for its whole run, edge to edge, at one spacing -- which is a
    // weave.
    //
    // The composite already draws its stroke through exactly this idea
    // (alongVary: "waxing and waning ALONG the crest, so a run reads as separate
    // strokes of different lengths rather than one unbroken rule across the
    // frame"). The injection had no equivalent, so the FOAM -- which is most of
    // what the eye reads out here -- was uniform even where the stroke was not.
    //
    // Two scales, because one gives a single blotch size. formEnv carries the
    // wave-group envelope, so a crest in a weak group breaks less than one in a
    // strong group, and the noise scrolls with the swell so a patch belongs to
    // the water rather than to the screen.
    float formEnv = texture(texPath, uv).y;
    float patchN = noiseAt(px + loopScroll(uDirDeep, 6.0, uInjPatchScale), uInjPatchScale) * 0.62
                 + noiseAt(px * 1.7 + loopScroll(uDirDeep, 9.0, uInjPatchScale * 0.38) + 91.0,
                           uInjPatchScale * 0.38) * 0.38;
    float patch = smoothstep(uInjPatch, uInjPatch + 0.30, formEnv * (0.40 + 0.90 * patchN));
    patch = mix(1.0, patch, uInjFilament);

    vec2 tang = normalize(vec2(-uDirDeep.y, uDirDeep.x));
    float wcRun = whitecap, brRun = breaking;
    for (int i = 1; i <= 5; ++i) {
        vec2 o = tang * (uInjCrestRun * float(i) / 5.0) / uRes;
        vec4 fA = texture(texFlow, uv + o), fB = texture(texFlow, uv - o);
        wcRun = max(wcRun, max(fA.w, fB.w));
        brRun = max(brRun, max(texture(texGeom, uv + o).w, texture(texGeom, uv - o).w));
    }
    // Only where the stroke is actually being drawn: off the crest contour this
    // would smear breaking across open water.
    float alongRun = mix(1.0, crestLine, uInjFilament);
    breaking = mix(breaking, max(breaking, brRun), alongRun);
    whitecap = mix(whitecap, max(whitecap, wcRun), alongRun);
    // The shore band is 46 TUNED px wide -- at map zooms that is most of the
    // visible water around a coast, and its unconditional floor injection
    // painted foam dashes over the whole shelf after every other source was
    // gated (this was the LAST author of the capital-tier fabric, found by
    // elimination). The immediate swash line keeps its foam at every zoom;
    // the wider band fades with breaker resolvability like breaking itself.
    // RETRACTED READING, kept as a warning: this window was first set to
    // 1.0..3.2 on the claim that the world bake's depth tops out near 18
    // tuned px. It does not. Decoded from ocean-phase-r2's alpha with the
    // manifest's own depthMax and TUNED_PER_WORLD, live depth runs to 105
    // tuned px exactly as offline -- p50 86, with 36% of water inside the
    // 18 px shelf and 60% beyond 46. Measure the asset, never infer the
    // units from a symptom.
    float shoreVis = mix(uBreakVis, 1.0, 1.0 - sstep(2.0, 7.0, depthPx));
    // THE COAST IS NOT A FOAM GUTTER. That 0.30 was a floor: three tenths of
    // the shore injection arrived everywhere along the band whether or not a
    // wave was breaking there, so foam accumulated into a continuous white rim
    // following the coastline exactly -- the owner's "dense foam around the
    // coast... it needs to look like the water splashes on the cliff, not
    // collecting foam on the edge". This file's own note about the teal band
    // says the same thing about constant-width bands: they read as an outline
    // drawn around the land.
    //
    // Water hits a shore in BURSTS, at the places a wave happens to be
    // arriving, and the rest of the coast is dark between them. So the floor
    // drops to a trace (uShoreFloor), breaking carries the rest, and a
    // travelling noise along the shore clumps it further -- a set arrives HERE,
    // then over THERE, and never everywhere at once.
    float coastPatch = 0.20 + 1.35 * sstep(0.34, 0.78,
        noiseAt(px + loopScroll(uDirDeep, 7.0, 260.0), 260.0) * 0.66
      + noiseAt(px * 2.3 + vec2(77.0, 31.0), 110.0) * 0.34);
    float inj = (breaking * uInjBreak + whitecap * uInjWhitecap * deepFade) * lineGate * patch
              + shoreZone * uInjShore * shoreVis * coastPatch
                * (0.22 + 0.78 * clamp(hn, 0.0, 1.0))
                * (uShoreFloor + (1.0 - uShoreFloor) * breaking);
    inj *= water;

    // saturating accumulation: repeated breaking builds a real sheet of
    // whitewater instead of being clamped to one step's worth
    float grow = 1.0 - exp(-inj * uDt);
    fresh   = fresh + (1.0 - fresh) * grow;
    persist = max(persist, fresh * 0.94);
    float add = grow;

    // fresh foam resets its own material coordinate: newly created whitewater
    // has no history to carry
    mat = mix(mat, px, clamp(add * 1.6, 0.0, 1.0));

    // foam cannot exist on land
    fresh *= water;
    persist *= water;

    outFoam = vec4(clamp(fresh, 0.0, 1.6), clamp(persist, 0.0, 1.6), mat);
}
