#version 330
// Persistent foam state. Foam is never re-noised per frame: it is generated by
// breaking, carried by the surface flow, stretched, aged and only then faded.
// Channels: r fresh whitewater, g persistent foam, ba material coordinate.
in vec2 uv;
out vec4 outFoam;

#include "common.glsl"

uniform sampler2D texGeom, texFlow, texPrev;
uniform float uDt;
uniform float uTauFresh, uTauPersist;
uniform float uInjBreak, uInjWhitecap, uInjShore;
uniform float uRelax;        // seconds for material coords to relax back
uniform float uDiffuse;
uniform float uFoamBlend;   // per-step weight of the diffused neighbourhood
uniform float uFirst;        // 1.0 on the very first step

void main()
{
    vec2 px = uv * uRes;
    vec4 M = texture(texM, uv);
    float water = M.x;
    vec4 G = texture(texG, uv);
    float sdf = G.w;
    vec4 flow4 = texture(texFlow, uv);
    vec2 flow = flow4.xy;
    vec4 geom = texture(texGeom, uv);
    float breaking = geom.w;
    float whitecap = flow4.w;

    // ---- semi-Lagrangian backtrace ---------------------------------------
    vec2 back = px - flow * uDt;
    vec2 buv = clamp(back / uRes, vec2(0.0015), vec2(0.9985));
    vec4 prev = texture(texPrev, buv);

    // A touch of diffusion so sheets break into patches instead of staying solid
    // -- but only a touch. At 48 substeps a second, a 0.30 blend toward the
    // 1-px neighbourhood is near-total smoothing within a second of foam life,
    // and that, not the erosion field, is what made whitewater read as soft
    // cotton wool instead of painted surf.
    vec2 d = uDiffuse / uRes;
    vec4 blur = 0.25 * (texture(texPrev, buv + vec2(d.x, 0.0))
                      + texture(texPrev, buv - vec2(d.x, 0.0))
                      + texture(texPrev, buv + vec2(0.0, d.y))
                      + texture(texPrev, buv - vec2(0.0, d.y)));
    prev = mix(prev, blur, uFoamBlend);

    // ...and it must fade faster out there, too
    float tauP = uTauPersist * mix(1.0, 0.18, smoothstep(15.0, 38.0, max(texture(texP, uv).w, 0.35)));
    float fresh   = prev.r * exp(-uDt / max(uTauFresh, 1e-3));
    float persist = prev.g * exp(-uDt / max(tauP, 1e-3));

    // Material coordinates ride with the flow. A material coordinate is *carried*,
    // not offset: M(x, t+dt) = M(x - u dt, t). Adding (px - back) as well made the
    // field accumulate a per-step drift, which decorrelated neighbouring pixels
    // and turned the lace lookup into per-pixel noise.
    vec2 mat = prev.ba;
    if (uFirst > 0.5) mat = px;
    mat = mix(mat, px, clamp(uDt / max(uRelax, 1e-3), 0.0, 1.0));

    // ---- injection --------------------------------------------------------
    float shoreZone = M.y;
    float hn = texture(texGeom, uv).x;
    // Offshore whitecap foam must not accumulate. In deep water a whitecap is a
    // transient streak on one crest; letting it build with the same persistence
    // as shore whitewater grew solid white slabs that read as ice floes.
    float depthPx = max(texture(texP, uv).w, 0.35);
    float deepFade = 1.0 - 0.93 * smoothstep(15.0, 38.0, depthPx);
    float inj = breaking * uInjBreak
              + whitecap * uInjWhitecap * deepFade
              + shoreZone * uInjShore * (0.22 + 0.78 * clamp(hn, 0.0, 1.0)) * (0.30 + 0.70 * breaking);
    inj *= water;

    // saturating accumulation: repeated breaking builds a real sheet of
    // whitewater instead of being clamped to one step's worth
    float grow = 1.0 - exp(-inj * uDt);
    fresh   = fresh + (1.0 - fresh) * grow;
    persist = max(persist, fresh * 0.94);
    float add = grow;

    // fresh foam resets its own material coordinate: newly created whitewater
    // has no history to carry
    mat = mix(mat, px, clamp(add * 1.6, 0.0, 1.0));

    // foam cannot exist on land
    fresh *= water;
    persist *= water;

    outFoam = vec4(clamp(fresh, 0.0, 1.6), clamp(persist, 0.0, 1.6), mat);
}
